import { defineConfig } from "@apps-in-toss/web-framework/config";

// Apps in Toss WebView mini-app config (generated by `npx ait init`, tuned here).
// Build output goes to `outdir`. Replace test ad ids / brand assets before release.
export default defineConfig({
  appName: "ismsp-studying",
  brand: {
    displayName: "ISMS-P 결함 판단 훈련",
    primaryColor: "#146c6c",
    icon: "",
  },
  web: {
    host: "localhost",
    port: 5173,
    commands: {
      dev: "vite dev",
      build: "vite build",
    },
  },
  permissions: [],
  outdir: "dist",
});
